### ISSUE TITLE
你好，如果原站是仅支持https访问的话，部署之后访问会提示这个

### ISSUE THREAD

**Issue by goxofy** [Yongke/aerproxy#1]
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx

**Comment by Yongke** [comment]
你好，刚刚改了一下。然后没有测试;-)
麻烦你试试最新的代码呢， 并且将配置里的PROXY_PASS_SCHEME改成https

```yml
env_variables:
 PROXY_PASS_HOST_PORT: 'your_ddns_domain_name:port'
 PROXY_PASS_SCHEME: 'http'
```
